# Generated by Django 4.0.4 on 2022-04-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='blog/thumbnails/cybs.png', upload_to='blog/thumbnails'),
        ),
    ]
